"""
Crisis & harm-reduction resources: national (Spain, always shown) plus an
explicitly configured local set (default: Comunidad de Madrid). Transcribed
verbatim from the spec docs (docs 3, 6, 8, 15, 16). These are static,
server-owned content — never generated by the LLM — so they cannot drift
or be "softened" by a model.

IMPORTANT: verify these phone numbers / services are still current before
any real-world use. They were current as documented in the source specs
but this app does not re-verify them at runtime.
"""

# National resources (Spain). ALWAYS present, whatever the local setting.
NATIONAL_CRISIS_RESOURCES = [
    {"name": "Línea 024", "description": "Atención a la conducta suicida (24h, España)", "contact": "024",
     "scope": "nacional", "region": "España"},
    {"name": "112", "description": "Emergencias", "contact": "112", "scope": "nacional", "region": "España"},
]

# Local resources, keyed by the deployment's configured region
# (``LOCAL_RESOURCES_REGION``). They are only shown, and labelled with their
# region, when that region is configured. "none" shows national ones only.
LOCAL_RESOURCE_SETS: dict[str, dict] = {
    "madrid": {
        "label": "Comunidad de Madrid",
        "resources": [
            {"name": "Centro Sanitario Sandoval", "description": "Salud sexual, Madrid",
             "contact": "https://www.comunidad.madrid/hospital/sandoval"},
            {"name": "Red CAD",
             "description": "Centros de Atención a las Adicciones, Madrid Salud (Ayuntamiento de Madrid)",
             "contact": "https://www.madrid.es/portales/munimadrid/es/Inicio/Salud/Adicciones"},
            {"name": "Apoyo Positivo", "description": "Apoyo en salud sexual y chemsex", "contact": "https://apoyopositivo.org"},
            {"name": "Imagina MÁS", "description": "Salud sexual y comunitaria LGTBI+", "contact": "https://imaginamas.org"},
            {"name": "COGAM (programa ChemSex)", "description": "Colectivo LGTB+ de Madrid", "contact": "https://cogam.es"},
            {"name": "Energy Control", "description": "Información y análisis sobre drogas (incl. Chem-Safe)",
             "contact": "https://energycontrol.org"},
        ],
    },
}


def crisis_resources(region: str | None = None) -> list[dict[str, str]]:
    """National resources first (always), then the configured local set, labelled."""
    if region is None:
        from app.config import get_settings

        region = get_settings().local_resources_region
    key = (region or "none").strip().lower()
    local = LOCAL_RESOURCE_SETS.get(key)
    items = [dict(item) for item in NATIONAL_CRISIS_RESOURCES]
    if local:
        items.extend({**item, "scope": "local", "region": local["label"]} for item in local["resources"])
    return items


def local_resources_label(region: str | None = None) -> str | None:
    if region is None:
        from app.config import get_settings

        region = get_settings().local_resources_region
    local = LOCAL_RESOURCE_SETS.get((region or "none").strip().lower())
    return local["label"] if local else None


# Backwards-compatible constant for the crisis reply (computed at import from
# the configured region; national resources are always included).
CRISIS_RESOURCES = crisis_resources()

# ----------------------------------------------------------------------
# Exact, server-owned message templates (doc 15 & doc 16). The LLM may
# only add a short warm sentence around these; it must never rewrite them.
# ----------------------------------------------------------------------

LEVEL4_PATIENT_MESSAGE = (
    "Detectamos que puedes estar pasando por un momento de mucho sufrimiento.\n\n"
    "Por favor, contacta ahora mismo con ayuda profesional:\n"
    "• Línea 024 (atención a la conducta suicida)\n"
    "• 112 (emergencias)\n\n"
    "No estás solo. Puedo quedarme aquí contigo mientras haces la llamada."
)

LEVEL3_PATIENT_MESSAGE = (
    "Hemos detectado una variación importante en tu ritmo de los últimos días.\n\n"
    "No significa que estés en peligro inmediato, pero sí que puede ser buen momento "
    "para cuidarte con más atención.\n\n"
    "Puedes usar la Metáfora de la Ola o revisar tu plan de seguridad."
)

LEVEL3_PATIENT_MESSAGE_WITH_PROFESSIONAL = (
    LEVEL3_PATIENT_MESSAGE + "\n\nTu profesional de referencia ha sido informado para que pueda acompañarte mejor."
)

LEVEL3_PROFESSIONAL_NOTIFICATION_TEMPLATE = (
    "Alerta Nivel 3 – Desviación estructural\n"
    "Paciente: {patient_label}\n"
    "structural_score en banda inestable.\n"
    "Se adjunta resumen de tendencias de los últimos 14 días.\n"
    "Requiere revisión cuando te sea posible."
)

LEVEL4_PROFESSIONAL_NOTIFICATION_TEMPLATE = (
    "ALERTA NIVEL 4 – REVISIÓN CLÍNICA URGENTE\n"
    "Paciente: {patient_label}\n"
    "Señal de ideación activa o crisis grave que requiere valoración humana.\n"
    "Se ha mostrado al paciente redirección a 024 y 112.\n"
    "Requiere revisión clínica urgente; la alerta no confirma por sí sola una emergencia."
)

# Techniques that must NEVER be suggested to this population (doc 3 & 8):
# TIPP "T" component (cold/pain-based grounding) — ice on face, ice-water
# immersion, rubber-band snapping, or any other self-harm-adjacent
# sensation. Safe alternatives only.
FORBIDDEN_TECHNIQUES = [
    "hielo en la cara",
    "inmersión en agua helada",
    "gomas elásticas",
    "dolor físico como técnica de grounding",
]

SAFE_GROUNDING_ALTERNATIVES = [
    "Sostener un objeto con textura marcada (p. ej. una piedra, tela rugosa)",
    "Presionar los pies con fuerza contra el suelo",
    "Un sabor intenso pero seguro (cítrico, menta fuerte)",
    "Respiración de suspiro fisiológico (inhalación doble por nariz + exhalación larga por boca)",
]
